# Generated by Django 4.1.2 on 2022-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('albumId', models.IntegerField(default=0)),
                ('photo', models.ImageField(height_field='photo_height', upload_to='photos/', width_field='photo_width')),
                ('url', models.URLField(blank=True)),
                ('photo_width', models.IntegerField(default=0, null=True)),
                ('photo_height', models.IntegerField(default=0, null=True)),
                ('thumbnailUrl', models.URLField(blank=True)),
            ],
        ),
    ]
