# Generated by Django 4.1.2 on 2022-10-27 14:10

from django.db import migrations, models
import django.db.models.deletion
import photoStorage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('photo', models.ImageField(height_field='photo_height', upload_to=photoStorage.models.Photo.photo_url, width_field='photo_width')),
                ('photo_width', models.IntegerField(default=0)),
                ('photo_height', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoStorage.album')),
            ],
        ),
    ]
